# Generated by Django 4.2.10 on 2024-03-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='next_level_experience',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
