# Generated by Django 4.2.10 on 2024-04-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
