# Generated by Django 4.2.10 on 2024-04-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testquestion_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(blank=True, default=50),
            preserve_default=False,
        ),
    ]
