# Generated by Django 4.2.10 on 2024-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_testattempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
