# Generated by Django 4.2.10 on 2024-03-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_test_testquestion_testattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='explanation',
        ),
        migrations.AddField(
            model_name='employee',
            name='karma',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='TestAttemptQuestionExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testattempt')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testquestion')),
            ],
            options={
                'unique_together': {('test_attempt', 'test_question')},
            },
        ),
        migrations.AddField(
            model_name='testattempt',
            name='question_explanations',
            field=models.ManyToManyField(through='main.TestAttemptQuestionExplanation', to='main.testquestion'),
        ),
    ]
