# Generated by Django 4.2.10 on 2024-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_testquestion_question_type_answeroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testquestion',
            old_name='explanation',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
    ]
