# Generated by Django 4.2.10 on 2024-04-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_testattempt_selected_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='selected_answers',
        ),
    ]
