# Generated by Django 4.2.10 on 2024-03-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_explanation_testquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='options',
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='main.testquestion')),
            ],
        ),
    ]
