# Generated by Django 4.2.10 on 2024-04-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_testattempt_selected_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='selected_answers',
            field=models.ManyToManyField(related_name='selected_answers', to='main.answeroption'),
        ),
    ]
