# Generated by Django 4.2.10 on 2024-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_testquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroption',
            old_name='text',
            new_name='option_text',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='selected_answers',
            field=models.ManyToManyField(to='main.answeroption'),
        ),
    ]
