# Generated by Django 4.2.10 on 2024-04-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testattempt_selected_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='selected_answers',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='submitted_answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='submitted_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
