# Generated by Django 4.2.10 on 2024-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_text_answeroption_option_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='required_experience',
        ),
        migrations.RemoveField(
            model_name='test',
            name='required_karma_percentage',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='question_explanations',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='answer_files/'),
        ),
        migrations.AddField(
            model_name='test',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='test',
            name='passing_score',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
