# Generated by Django 4.2.10 on 2024-03-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_test_required_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
