# Generated by Django 4.2.10 on 2024-03-26 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_testquestion_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='test',
            name='acoin_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='allow_retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='test',
            name='experience_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='min_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='required_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='show_correct_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='theme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='unlimited_time',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
