# Generated by Django 4.2.10 on 2024-03-26 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_remove_test_duration_minutes_test_acoin_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='balance',
        ),
        migrations.AlterField(
            model_name='acoin',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acoin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acoin', to=settings.AUTH_USER_MODEL),
        ),
    ]
