# Generated by Django 4.2.10 on 2024-03-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_employee_balance_alter_acoin_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acoin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acointransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='acoin',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='acointransaction',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
    ]
