# Generated by Django 4.2.10 on 2024-05-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_test_max_score_alter_testattempt_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='required_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.test'),
        ),
    ]
