# Generated by Django 4.2.10 on 2024-05-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_test_author_test_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAttemptQuestionExplanation',
        ),
    ]
