# Generated by Django 4.2.10 on 2024-05-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_testattemptquestionexplanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='min_level',
        ),
        migrations.AddField(
            model_name='test',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
