# Generated by Django 4.2.10 on 2024-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_testquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='question_images/'),
        ),
    ]
