# Generated by Django 4.2.10 on 2024-05-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_test_min_level_test_min_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='test/'),
        ),
    ]
