# Generated by Django 4.2.10 on 2024-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_testquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='question_files/'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
