# Generated by Django 4.2.10 on 2024-04-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_testquestion_file_alter_testquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='file',
        ),
    ]
