# Generated by Django 4.2.10 on 2024-05-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_employee_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='is_correct',
        ),
    ]
