# Generated by Django 4.2.10 on 2024-04-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_theory'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.achievement'),
        ),
    ]
