# Generated by Django 4.2.10 on 2024-05-22 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_testattempt_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
