# Generated by Django 4.2.10 on 2024-05-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_testattempt_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('Passed', 'Пройден'), ('Not Started', 'Не начат'), ('In Progress', 'В процессе'), ('Failed', 'Не пройден'), ('На модерации', 'На модерации'), ('ТЕСТ', 'ТЕСТ')], default='Not Started', max_length=20),
        ),
    ]
