# Generated by Django 4.2.10 on 2024-04-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_test_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='test',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('Passed', 'Пройден'), ('Not Started', 'Не начат'), ('In Progress', 'В процессе'), ('Failed', 'Не пройден')], default='Not Started', max_length=20),
        ),
    ]
