# Generated by Django 4.2.10 on 2024-04-03 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_testattempt_is_completed_test_total_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('Test', 'За тест'), ('Requests', 'За количество обращений')], default='Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classifications'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='required_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
