# Generated by Django 4.2.10 on 2024-04-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_achievement_type_alter_achievement_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeachievement',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='acointransaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
    ]
