# Generated by Django 4.2.10 on 2024-04-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_employeeachievement_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acointransaction',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
