# Generated by Django 4.2.10 on 2024-04-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_acointransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acointransaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
