# Generated by Django 4.2.10 on 2024-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_employeeachievement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
