# Generated by Django 4.2.10 on 2024-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_testattempt_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='can_attempt_twice',
            field=models.BooleanField(default=False),
        ),
    ]
