# Generated by Django 4.2.10 on 2024-04-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_testattempt_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='max_level',
            field=models.IntegerField(default=3),
        ),
    ]
