# Generated by Django 4.2.10 on 2024-04-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_achievement_max_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theory',
            name='position',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10),
        ),
        migrations.AddField(
            model_name='theory',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.testquestion'),
            preserve_default=False,
        ),
    ]
