# Generated by Django 4.2.10 on 2024-04-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_theory_test_test_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theory',
            name='position',
            field=models.CharField(choices=[('before', 'Before questions'), ('after', 'After questions')], default='before', max_length=10),
        ),
        migrations.AlterField(
            model_name='theory',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testquestion'),
        ),
    ]
