# Generated by Django 4.2.10 on 2024-04-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_theory_test_alter_theory_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
