# Generated by Django 4.2.10 on 2024-04-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_theory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
