# Generated by Django 4.2.10 on 2024-04-16 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_theory_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
