# Generated by Django 4.2.10 on 2024-04-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_test_introduction_alter_test_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
    ]
