# Generated by Django 4.2.10 on 2024-04-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_theme_alter_test_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.theme'),
        ),
    ]
