# Generated by Django 4.2.10 on 2024-04-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_achievement_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classifications'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='required_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
