# Generated by Django 4.2.10 on 2024-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_achievement_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='required_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_currency',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
