# Generated by Django 4.2.10 on 2024-04-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_achievement_required_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
