# Generated by Django 4.2.10 on 2024-04-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='achievements/'),
        ),
    ]
