# Generated by Django 4.2.10 on 2024-04-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='request_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.classifications'),
        ),
    ]
