# Generated by Django 4.2.10 on 2024-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_achievement_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifications',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
